# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RsTnlTdVoLdfav8-5ck0WItLig3kJC46
"""
import numpy as np
import matplotlib.pyplot as plt 
from hw3_py import GBM, Option
import scipy.optimize as so
from prettytable import PrettyTable

'''
Code here is used to read data in src file

'''
#------------------
## Code starts here
#------------------

Odata=np.loadtxt('optiondata2.dat', comments='#', delimiter=',')

gbm = GBM(
    init_state = 100, #market data
    drift_ratio = .05, #market data
    vol_ratio = .1 #initial guess
)

def Clist(Odata):
  Olist=[]
  for row in Odata:
    otype, maturity, strike, option_price=row
    Olist.append(Option(Otype=otype, Strike=strike, Maturity=maturity, Market_Price=option_price))
  return Olist

def err_function(vol, gbm, Olist):
  gbm.vol_ratio=vol
  err=0
  for option in Olist:
    err=err+(GBM.bsm_price(gbm, option)-option.Market_Price)**2
  return err

def calibration_bsm(gbm, Olist):
  init_vol=.1
  return so.fmin(err_function, init_vol, args = (gbm, Olist), disp = 0)[0]



